### ISSUE TITLE
WASM support?

### ISSUE THREAD

**Issue by nazar-pc** [rust-rse/reed-solomon-erasure#52]
As part of my work at Subspace Labs I've made a port of this awesome library to WebAssembly such that it runs in browser and Node.js environments: https://github.com/subspace/reed-solomon-erasure.wasm
I had to do some tweaks though, because despite successful compilation, Rayon internals were failing in runtime with panic trying to figure out how many CPU cores there are when deciding on parallelism: https://github.com/subspace/reed-solomon-erasure/commit/85f8dcb4cefa2f226c9ba178093585d69598f3a0

So basically I'd like to ask 2 questions here:
1) Could you tweak the library such that we don't have to create a fork in order to compile it to WASM?
2) Would you like to absorb WASM support into this upstream library such that we don't have to catch-up with upstream all the time?

I'm Rust newbie, so any suggestions on code improvements are welcome.
Maybe you can tweak library API to make WASM port even more optimized.
And I know there are still some places in JS-WASM glue that can be optimized for fewer memory copy operations.

**Comment by darrenldl** [comment]
**Preface**: I am still away atm, so I won't be touching this until September it seems, and so my reply may not be very detailed or relevant as I haven't looked into the code base in a while.

> As part of my work at Subspace Labs I've made a port of this awesome library to WebAssembly such that it runs in browser and Node.js environments: https://github.com/subspace/reed-solomon-erasure.wasm

Interesting work! Never crossed my mind to use it in web stuff. Glad you find it awesome, haha - this library definitely took me a ridiculous amount of time for the first few versions.

> I had to do some tweaks though, because despite successful compilation, Rayon internals were failing in runtime with panic trying to figure out how many CPU cores there are when deciding on parallelism: subspace@85f8dcb

Hm okay, that's good to know on my end. Right now Rayon basically helps coding operations to scale properly when number of parity shards increases. Dropping it means there may be a small factor of slow down (instead of coding multiple parity shards at once, they are coded one by one).

> 1. Could you tweak the library such that we don't have to create a fork in order to compile it to WASM?

I know Rayon provides [build_global](https://docs.rs/rayon/1.1.0/rayon/struct.ThreadPoolBuilder.html#method.build_global) to set the number of threads directly, but I have not tried it yet, and don't know if it'll avoid the panic you mentioned. I'll try this when I get back.

> 2. Would you like to absorb WASM support into this upstream library such that we don't have to catch-up with upstream all the time?

I'm completely new to WASM and npm, so I'm gonna ask a few silly questions.

1. As it seems that WASM object is a binary object, I presume it is usually not checked into git repos?

2. Must the .wasm binary object be in the git repo for npm publishing to work? Or can I package artifacts separately then publish that?

**Comment by nazar-pc** [comment]
> Dropping it means there may be a small factor of slow down (instead of coding multiple parity shards at once, they are coded one by one).

Making it use single thread just for `wasm32-unknown-unknown` target would be enough. BTW, WebAssembly should gain multi-threading support soon-ish, so it would be beneficial to be able to add such support back when that become available in browsers and Node.js.

> I'm completely new to WASM and npm, so I'm gonna ask a few silly questions.

1. Yes, it is a binary build artifact, I typically check it into source tree for convenience, for instance when running tests on top of source TypeScript code without separate compilation step or when you want to do experiments and don't want to install the whole build toolchain (in this case for both Rust and Node.js/TypeScript)
2. `dist` directory is what would be published to NPM and it is not in git, thus no, you don't have to have wasm in git in order to be able to publish to NPM, it is totally optional

**Comment by darrenldl** [comment]
Thanks for the quick reply!

> Making it use single thread just for wasm32-unknown-unknown target would be enough. BTW, WebAssembly should gain multi-threading support soon-ish, so it would be beneficial to be able to add such support back when that become available in browsers and Node.js.

I think I'll look into putting it behind a build flag - I vaguely recall there was similar need for when building for no-std environment.

For binary artifacts, I'm mainly concerned about reproducibility - do I need to go out of my way to ensure the build produced is a reproducible build or do most tool chains (or specifically the one you're using) offer that already?

**Comment by nazar-pc** [comment]
It is not reproducible yet and I was also a bit concerned about that. I may look into something that will strip non-deterministic info from the binary to make it fully reproducible if needed.

**Comment by darrenldl** [comment]
If it's from a single authoritative source (say from CI), then it's fine-ish. Or at least I'm fine with that for my other binary projects.

But since I don't know if one can publish things through CI (or at least I'm not aware of ways to transfer credentials securely to a CI worker), I think reproducible build is needed as an assurance to users.

But for the initial versions, maybe that's fine I think, but does mean injecting some risk that might backfire later on.

**Comment by nazar-pc** [comment]
For NPM you should be able to issue a token with write access, add it as a secret to Travis CI and use for publishing to NPM in automated fashion.

**Comment by darrenldl** [comment]
Oh okay, then yeah sure, I'm happy to have this repo take care of WASM builds in that case.

**Comment by darrenldl** [comment]
Just FYI, I've got a bit of free time atm, and will try to wrap most issues up over next 2-3 weeks, including this one.

**Comment by darrenldl** [comment]
Hey @nazar-pc 

I'm clearing the backlog actively this week, but still on a (very) limited time budget.

Mind if I ask a few questions to help me speed up the process?

1. What's the procedure/command for building the WASM binary object? Any dependencies associated?
2. Any pointers for procedure for setting up automated NPM publishing?

**Comment by nazar-pc** [comment]
1.a. For WASM itself there are just 2 dependencies in the project itself: one is `wasm-bindgen` that creates a convenient bridge to WebAssembly from Rust and another is `wee_alloc`, small memory allocator for optimal size on the WEB: https://github.com/subspace/reed-solomon-erasure.wasm/blob/master/Cargo.toml
1.b. You have to have `wasm-pack` installed on your system in order for build to work
1.c. For NPM you'll also need to build TypeScript code to JavaScript. You can re-use this dependencies definition, which also includes package used for testing: https://github.com/subspace/reed-solomon-erasure.wasm/blob/master/package.json, globally you only need to install Node.js, which typically comes with package manager NPM out of the box
1.d. `scripts` section of above file contains all of the commands you need to run to build everything from Rust to final JavaScript files. Just install Node.js, clone repo, go into its directory and run `npm run build`, you can also read there what it will do exactly.
2.a. You have to edit `package.json`'s `name` to either include your NPM namespace or just use global `reed-solomon-erasure.wasm` which is not occupied yet, and other details accordingly as well as do `npm login` into your account
2.b. Once you've built everything, artifacts will be in `dist` directory; just run `npm publish` and it will be on NPM
2.c. Once that works, you can go to https://www.npmjs.com/settings/you-account/tokens and create a read/write token for automated publish and store it as encrypted file in the repo (see https://docs.travis-ci.com/user/encryption-keys/) that will be decrypted to `.npmrc` with singe line `//registry.npmjs.org/:_authToken=your-token-here`
2.d. Then you should be able to do `npm run build && npm run publish` from Travis CI

Sorry, it is not trivial, but not too difficult either. I'd be happy to assist be there any difficulties.

**Comment by darrenldl** [comment]
Gonna ask some silly questions (things I can probably google but even spending a few hours on this is a bit extravagant for me right now).

So to build the WASM artifact, I can just create a second package here which depends on `reed-solomon-erasure` right? I am mainly concerned about adding dependencies directly to `reed-solomon-erasure` that only get used in WASM workflow.

If I can make a say, `reed-solomon-erasure.wasm` package (borrowing your name), in this repo, that depends on local copy of `reed-solomon-erasure`, and the build WASM artifact that way, that'll be the best.

I've at least set up my NPM account (yay, first step), so I'll give it a proper shot after Thursday where my time frees up a bit.

**Comment by nazar-pc** [comment]
Yes, creating second wasm-specific package seems fine to me. Your plan is pretty much how I see it as well.

**Comment by darrenldl** [comment]
@nazar-pc I'm working on wasm builds at the `wasm` branch, copying your code and stuff as I go.

Right now I'm just having the package under the `wasm` directory, let me know if you think a different layout would be better - I'm not very familiar with conventions with multiple (sub) packages in a git repo.

**Comment by darrenldl** [comment]
I also need to make some interface changes with your code, which I've copied over to this repo.

I'll ping you when the changes are in place to let you see if it's still ergonomic to use from JS/TS side.

I've also updated the README.md (at wasm branch) credits section, see if you're happy with the acknowledgement statements [here](https://github.com/darrenldl/reed-solomon-erasure/tree/wasm#wasm-builds)

**Comment by nazar-pc** [comment]
`wasm` directory seems alright to me and readme changes make sense 👍

**Comment by darrenldl** [comment]
@nazar-pc It seems that a new ReedSolomon struct is constructed in every `encode` and `reconstruct`, I'm curious if this can be improved?

Also are `encode` and `reconstruct` the only functions needed?

**Comment by nazar-pc** [comment]
I'm not sure how expensive creating that struct actually is. If it is indeed relatively expensive, it would be better to create it once and then reuse (something like a struct address should be exposed in that case I guess).

Those are the only 2 functions we were needing at Subspace, but I can see more of the low-level functions being exposed in the future for those who need them. Having just those 2 functions initially makes an API useful and not hard to actually use (despite not being the most efficient  for sure).

**Comment by darrenldl** [comment]
I presume one can create an object in TS as well right? Trying to gauge if it's doable to have a single instance in TS.

Also just FYI, I've updated `wasm` branch to conform to new API as well, in case that's useful to your group.

**Comment by nazar-pc** [comment]
Yes, `class ReedSolomonErasure` is what object is created from (TypeScript is essentially just a syntaxic sugar with type checking for JavaScript).
So instead of specifying data and parity shards in methods, those will be constructor arguments, struct will be instantiated once in constructor and reference to struct will be stored and passed along internally in subsequent method calls.

**Comment by darrenldl** [comment]
Okay brilliant! I'll experiment with that a bit then.

I'll just look into publishing WASM to NPM first for now, and do the API changes in future.

**Comment by nazar-pc** [comment]
Library now compiles to wasm just fine, also there is a legacy package on NPM. Nothing left to be done here, closing.

**Comment by nazar-pc** [comment]
> Are you aware that we abandoned this this crate for polkadot/kusama?

Yes, I am aware. We have 128 data and 128 parity shards in Subspace right now with GF(2^16), which seems to be a different use case than one you have in Polkadot/Kusama. I'm very far from being an expert in erasure coding though, merely just a user.
